services:
  redis:
    container_name: redis
    image: redis:8.0.3
    restart: unless-stopped
    volumes:
      - /data/app/redis-data:/data
    networks:
      - app_net
    ports:
      - 6379:6379
    command: redis-server --port 6379 --appendonly yes
    labels:
      - "name=redis"
      - "mode=standalone"

networks:
  app_net:
    external: true
