services:
  elastic:
    container_name: elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
    restart: unless-stopped
    ports:
      - 9200:9200
    volumes:
      - /data/apm/elastic-data:/usr/share/elasticsearch/data
    networks:
      - apm_net
    environment:
      - discovery.type=single-node
      - node.name=elastic
      - ELASTIC_PASSWORD=${elastic_password}
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - xpack.license.self_generated.type=basic
      - ES_JAVA_OPTS=-Xms1024m -Xmx1024m
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -u \"elastic:${elastic_password}\" http://localhost:9200/_cluster/health | grep -q '\"status\":\"green\"\\|\"status\":\"yellow\"'",
        ]
        # curl -s -u "elastic:${elastic_password}" http://localhost:9200/_cluster/health | \
        #   grep -q '\"status\":\"green\"\\|\"status\":\"yellow\"'
      interval: 10s
      timeout: 10s
      retries: 120
    ulimits:
      memlock:
        soft: -1
        hard: -1


  elastic-users:
    container_name: elastic-users
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
    restart: no
    depends_on:
      elastic:
        condition: service_healthy
    networks:
      - apm_net
    command: >
      bash -c '
        echo "Waiting for Elasticsearch availability";
        until curl -s -u "elastic:${elastic_password}" http://elastic:9200/_cluster/health | grep -q "\"status\":\"green\"\\|\"status\":\"yellow\""; do echo "Waiting for Elasticsearch availability -> " $((idx++)); sleep 1; done;
        echo "Setting kibana_system password";
        until curl -s -X POST -u "elastic:${elastic_password}" -H "Content-Type: application/json" http://elastic:9200/_security/user/kibana_system/_password -d "{\"password\":\"${kibana_password}\"}" | grep -q "^{}"; do sleep 3; done;
        echo "All done!";
      '
    user: "0"


  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.14.3
    restart: unless-stopped
    depends_on:
      elastic:
        condition: service_healthy
    ports:
      - 5601:5601
    volumes:
      - /data/apm/kibana-data:/usr/share/kibana/data
    networks:
      - apm_net
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=http://elastic:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${kibana_password}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

networks:
  apm_net:
    external: true
