services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:2.528-jdk17
    restart: unless-stopped
    ports:
      - 8082:8080
      - 50000:50000
    volumes:
      - jenkins_data:/var/jenkins_home
  
  jenkins-agent:
    container_name: jenkins-agent
    image: jenkins/ssh-agent:jdk17
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true

volumes:
  jenkins_data:
