services:
  jenkins:
    image: jenkins/jenkins:2.528-jdk17
    restart: unless-stopped
    container_name: jenkins
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins_data:/var/jenkins_home
  
  jenkins-agent:
    image: jenkins/ssh-agent:jdk17
    restart: unless-stopped
    container_name: jenkins-agent
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins_data:
