services:
  gitlab:
    container_name: gitlab
    image: gitlab/gitlab-ce:17.4.5-ce.0
    restart: unless-stopped
    ports:
      - 8443:443
    volumes:
      - gitlab_data:/var/opt/gitlab
      - gitlab_conf:/etc/gitlab
      - ./conf/gitlab.rb:/etc/gitlab/gitlab.rb
      - gitlab_logs:/var/log/gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url '${external_url}'
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
    shm_size: 256m

volumes:
  gitlab_data:
  gitlab_conf:
  gitlab_logs:
