services:
  redis:
    image: redis:8.0.3
    container_name: redis
    ports:
      - 6379:6379
    restart: unless-stopped
    labels:
      - "name=redis"
      - "mode=standalone"
    volumes:
      - redis_data:/data
    command: redis-server --port 6379 --appendonly yes
    network_mode: host
    #networks:
    #  - local-default

volumes:
  redis_data:

networks:
  local-default:
    external: true
