services:
  n8n-postgres:
    container_name: n8n-postgres
    image: postgres:14.18
    restart: unless-stopped
    volumes:
      - ./n8n-initdb.sh:/docker-entrypoint-initdb.d/n8n-initdb.sh
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${postgres_db}
      POSTGRES_USER: ${postgres_user}
      POSTGRES_PASSWORD: ${postgres_password}
      n8n_postgres_db: ${n8n_postgres_db}
      n8n_postgres_user: ${n8n_postgres_user}
      n8n_postgres_password: ${n8n_postgres_password}
    healthcheck:
      test: >
        pg_isready -U ${postgres_user} -d ${postgres_db} && 
        pg_isready -U ${n8n_postgres_user} -d ${n8n_postgres_db}
      interval: 5s
      timeout: 3s
      retries: 5

  n8n:
    container_name: n8n
    image: docker.n8n.io/n8nio/n8n
    restart: unless-stopped
    depends_on:
      n8n-postgres:
        condition: service_healthy
    ports:
      - 5678:5678
    volumes:
      - n8n_data:/home/node/.n8n
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=n8n-postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${n8n_postgres_db}
      - DB_POSTGRESDB_USER=${n8n_postgres_user}
      - DB_POSTGRESDB_PASSWORD=${n8n_postgres_password}
      - N8N_SECURE_COOKIE=false
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true

volumes:
  postgres_data:
  n8n_data:
