services:
  n8n-postgres:
    container_name: n8n-postgres
    image: postgres:14.18
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${postgres_db}
      POSTGRES_USER: ${postgres_user}
      POSTGRES_PASSWORD: ${postgres_password}
    volumes:
      - ./initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
      - postgres_data:/var/lib/postgresql/data

  n8n:
    container_name: n8n
    image: docker.n8n.io/n8nio/n8n
    restart: unless-stopped
    depends_on:
      - n8n-postgres
    ports:
      - 5678:5678
    volumes:
      - n8n_data:/home/node/.n8n
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRES_HOST=n8n-postgres
      - DB_POSTGRES_PORT=5432
      - DB_POSTGRES_DATABASE=${postgres_db}
      - DB_POSTGRES_USER=${postgres_non_root_user}
      - DB_POSTGRES_PASSWORD=${postgres_non_root_password}
      - N8N_SECURE_COOKIE=false
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true

volumes:
  postgres_data:
  n8n_data:
