services:
  nginx:
    container_name: nginx
    image: nginx:1.29
    restart: unless-stopped
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      # - ./nginx/conf/dhparams4096.pem:/dhparams4096.pem:ro
      #- /etc/letsencrypt/live/mm.mgkim.net/fullchain.pem:/cert_mm.mgkim.net.pem:ro
      #- /etc/letsencrypt/live/mm.mgkim.net/privkey.pem:/key_mm.mgkim.net.pem:ro
      #- /etc/letsencrypt/live/nexus.mgkim.net/fullchain.pem:/cert_nexus.mgkim.net.pem:ro
      #- /etc/letsencrypt/live/nexus.mgkim.net/privkey.pem:/key_nexus.mgkim.net.pem:ro
      #- /etc/letsencrypt/live/gitlab.mgkim.net/fullchain.pem:/cert_gitlab.mgkim.net.pem:ro
      #- /etc/letsencrypt/live/gitlab.mgkim.net/privkey.pem:/key_gitlab.mgkim.net.pem:ro
    networks:
      - web_net
    environment:
      TZ: UTC
    security_opt:
      - no-new-privileges:true
    pids_limit: 100
    read_only: true
    tmpfs:
      - /var/run
      - /var/log/nginx
      - /var/cache/nginx

networks:
  web_net:
    external: true
