services:
  postgres:
    container_name: postgres
    image: postgres:14.18
    restart: none
    environment:
      POSTGRES_DB: ${postgres_db}
      POSTGRES_USER: ${postgres_user}
      POSTGRES_PASSWORD: ${postgres_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  sonarqube:
    image: sonarqube:2025-lta-developer
    container_name: sonarqube
    restart: no
    ports:
      - 9000:9000
    depends_on:
      - postgres
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_temp:/opt/sonarqube/temp
      - sonarqube_extensions:/opt/sonarqube/extensions
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://postgres:5432/${postgres_db}
      - SONAR_JDBC_USERNAME=${postgres_user}
      - SONAR_JDBC_PASSWORD=${postgres_password}
      - SONAR_EMBEDDED_DATABASE_PORT=-1  # H2 비활성화
    ulimits:
     nofiles:
       soft: 65536
       hard: 65536
    mem_limit: 3g
  
volumes:
  postgres_data:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_conf:
  sonarqube_temp:
  sonarqube_extensions:
