services:
  postgres-sec:
    container_name: postgres-sec
    image: postgres:14.18
    restart: unless-stopped
    volumes:
      - ./initdb/initdb-keycloak.sh:/docker-entrypoint-initdb.d/initdb-keycloak.sh
      - /data/sec/postgres-data:/var/lib/postgresql/data
    networks:
      - sec_net
    environment:
      POSTGRES_DB: ${postgres_db}
      POSTGRES_USER: ${postgres_user}
      POSTGRES_PASSWORD: ${postgres_password}
      postgres_keycloak_db: ${postgres_keycloak_db}
      postgres_keycloak_user: ${postgres_keycloak_user}
      postgres_keycloak_password: ${postgres_keycloak_password}
    healthcheck:
      test: >
        pg_isready -U ${postgres_user} -d ${postgres_db} &&
        pg_isready -U ${postgres_keycloak_user} -d ${postgres_keycloak_db}
      interval: 5s
      timeout: 3s
      retries: 5

networks:
  sec_net:
    external: true
