services:
  mariadb:
    image: mariadb:11.8.2-ubi9
    container_name: mariadb
    ports:
      - 3306:3306
    restart: always
    environment:
      - TZ=Asia/Seoul
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=maria
      - MYSQL_ROOT_PASSWORD=${mysql_root_password}
      - MYSQL_USER=${mysql_user}
      - MYSQL_PASSWORD=${mysql_password}
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
