services:
  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    ports:
      - 9100:8081
      - 5000:5000
    restart: always
    volumes:
      - ./nexus_data:/nexus-data
    user: "root:root"

