services:
  cp-zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: cp-zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
    volumes:
      - cp-zookeeper_secrets:/etc/zookeeper/secrets
      - cp-zookeeper_data:/var/lib/zookeeper/data
      - cp-zookeeper_log:/var/lib/zookeeper/log
    restart: unless-stopped
    networks:
      - local-default

  cp-kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: cp-kafka
    ports:
      - 59092:59092
    restart: unless-stopped
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: cp-zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://cp-kafka:9092,EXTERNAL://mgkim.net:59092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    volumes:
      - cp-kafka_secrets:/etc/kafka/secrets
      - cp-kafka_data:/var/lib/kafka/data
    depends_on:
      - cp-zookeeper
    networks:
      - local-default

  cp-kafka-connect:
    image: docker.mgkim.net:5000/market/cp-kafka-connect:7.6.1
    container_name: cp-kafka-connect
    ports:
      - 8083:8083
    restart: unless-stopped
    environment:
      CONNECT_BOOTSTRAP_SERVERS: cp-kafka:9092
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: "market-"
      CONNECT_CONFIG_STORAGE_TOPIC: "market-config"
      CONNECT_OFFSET_STORAGE_TOPIC: "market-offsets"
      CONNECT_STATUS_STORAGE_TOPIC: "market-status"
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_REST_ADVERTISED_HOST_NAME: "localhost"
      CONNECT_LOG4J_ROOT_LOGLEVEL: INFO
      CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components/confluentinc-kafka-connect-jdbc/lib,/etc/kafka-connect/jars"
    volumes:
      - cp-kafka-connect_secrets:/etc/kafka-connect/secrets
      - cp-kafka-connect_jars:/etc/kafka-connect/jars
      - cp-kafka_secrets:/etc/kafka/secrets
      - cp-kafka_data:/var/lib/kafka/data
    depends_on:
      - cp-kafka
    networks:
      - local-default

volumes:
  cp-zookeeper_secrets:
  cp-zookeeper_data:
  cp-zookeeper_log:
  cp-kafka_secrets:
  cp-kafka_data:
  cp-kafka-connect_secrets:
  cp-kafka-connect_jars:

networks:
  local-default:
    external: true
