version: '3'
services:
  keycloak:
    image: keycloak/keycloak:26.0
    container_name: keycloak
    ports:
      - 8080:8080
    restart: unless-stopped
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: 1
    command: start-dev
    volumes:
      - ./keycloak/keycloak.conf:/opt/keycloak/conf/keycloak.conf
      - keycloak_data:/opt/keycloak/data
    networks:
      - local-default

volumes:
  keycloak_data:

networks:
  local-default:
    external: true
