services:
  postgres:
    container_name: postgres
    image: postgres:17.0
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - local-default

volumes:
  postgres_data:

networks:
  local-default:
    external: true
