services:
  zipkin:
    image: openzipkin/zipkin:3.4.2
    container_name: zipkin
    ports:
      - 9411:9411
    restart: unless-stopped
    environment:
      - STORAGE_TYPE=mem
    networks:
      - local-default

networks:
  local-default:
    external: true
