FROM amazoncorretto:8u462-al2023

WORKDIR /app

RUN dnf install -y unzip iputils nmap-ncat net-tools bash libxml2 \
    && curl -L https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -o /usr/local/bin/yq \
    && chmod +x /usr/local/bin/yq \
    && dnf clean all

USER root
RUN echo 'PS1="[\u@\h \w]\\$ "' >> /root/.bashrc

RUN mkdir -p /app/scouter
COPY amazoncorretto/scouter.agent-2.22.0.zip /app/scouter
RUN unzip /app/scouter/scouter.agent-2.22.0.zip -d /app/scouter/ \
    && rm /app/scouter/scouter.agent-2.22.0.zip

ENV LANG=ko_KR.UTF-8 \
    TZ=Asia/Seoul
